import { TagType, TCalendar } from "../interfaces/calendar.interface";

export const calendar: TCalendar = [
  {
    id: 1,
    name: "Janeiro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Segunda-feira",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 2,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 7,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 8,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 14,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 15,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 21,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 22,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 28,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 29,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 31,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },

  {
    id: 2,
    name: "Fevereiro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 4,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 5,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 11,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 12,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 18,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 19,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 25,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 26,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
  {
    id: 3,
    name: "Março",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_5",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 3,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 4,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 10,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 11,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 17,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 18,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 24,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 25,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 31,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
    ],
  },
  {
    id: 4,
    name: "Abril",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 7,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 8,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 14,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 15,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 21,
        week_day: "Domingo",
        is_holiday: true,
        is_weekend: true,
        tag: TagType.holidays, // Tiradentes
      },
      {
        day: 22,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 28,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 29,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
  {
    id: 5,
    name: "Maio",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Quarta-feira",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays, // Dia do Trabalho
      },
      {
        day: 2,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 5,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 6,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 12,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 13,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 19,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 20,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 26,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 27,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 31,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
  {
    id: 6,
    name: "Junho",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_5",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_6",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 2,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 3,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 9,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 10,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 16,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 17,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 23,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 24,
        week_day: "Segunda-feira",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays, // São João (feriado regional em alguns estados)
      },
      {
        day: 25,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 30,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
    ],
  },
  {
    id: 7,
    name: "Julho",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 7,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 8,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 14,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 15,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 21,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 22,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 28,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 29,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 31,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
  {
    id: 8,
    name: "Agosto",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 4,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 5,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 11,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 12,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 18,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 19,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 25,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 26,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 31,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
    ],
  },
  {
    id: 9,
    name: "Setembro",
    days: [
      {
        day: 1,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 2,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Sábado",
        is_holiday: true,
        is_weekend: true,
        tag: TagType.holidays, // Independência do Brasil
      },
      {
        day: 8,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 9,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 15,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 16,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 22,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 23,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 29,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 30,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
  {
    id: 10,
    name: "Outubro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 6,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 7,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Sábado",
        is_holiday: true,
        is_weekend: true,
        tag: TagType.holidays, // Nossa Senhora Aparecida
      },
      {
        day: 13,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 14,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 16,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 20,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 21,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 27,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 28,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 31,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
  {
    id: 11,
    name: "Novembro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 0,
        week_day: "blank_5",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays,
      },
      {
        day: 1,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 2,
        week_day: "Sábado",
        is_holiday: true,
        is_weekend: true,
        tag: TagType.holidays, // Finados
      },
      {
        day: 3,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 4,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 8,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 9,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 10,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 11,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 15,
        week_day: "Sexta-feira",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays, // Proclamação da República
      },
      {
        day: 16,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 17,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 18,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Quarta-feira",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays, // Consciência Negra (feriado regional em alguns estados)
      },
      {
        day: 21,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 22,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 23,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 24,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 25,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 26,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 29,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 30,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
    ],
  },
  {
    id: 12,
    name: "Dezembro",
    days: [
      {
        day: 1,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 2,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 3,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 4,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 5,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 6,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 7,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 8,
        week_day: "Domingo",
        is_holiday: true,
        is_weekend: true,
        tag: TagType.holidays, // Nossa Senhora da Conceição (feriado regional em alguns estados)
      },
      {
        day: 9,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 10,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 11,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 12,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 13,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 14,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 15,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 16,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 17,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 18,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 19,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 20,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 21,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 22,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 23,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 24,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 25,
        week_day: "Quarta-feira",
        is_holiday: true,
        is_weekend: false,
        tag: TagType.holidays, // Natal
      },
      {
        day: 26,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 27,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 28,
        week_day: "Sábado",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 29,
        week_day: "Domingo",
        is_holiday: false,
        is_weekend: true,
        tag: "",
      },
      {
        day: 30,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
      {
        day: 31,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
        tag: "",
      },
    ],
  },
];
