import { TCalendar } from "../interfaces/calendar.interface";

export const calendar: TCalendar = [
  {
    id: 1,
    name: "Janeiro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 1,
        week_day: "Segunda-feira",
        is_holiday: true,
        is_weekend: false,
      },
      { day: 2, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 3,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 4,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 5, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 6, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 7, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 8,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 9, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 10,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 13, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 14, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 15,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 20, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 21, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 22,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 25,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 27, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 28, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 29,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 30,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 31,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 2,
    name: "Fevereiro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 1,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 2, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 3, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 4, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 5,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 6, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 7,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 8,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 9, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 10, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 11, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 12,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 14,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 15,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 17, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 18, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 19,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 21,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 22,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 24, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 25, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 26,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 28,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 29,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 3,
    name: "Março",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_5",
        is_holiday: true,
        is_weekend: false,
      },
      { day: 1, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 2, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 3, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 4,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 5, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 6,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 7,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 8, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 9, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 10, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 11,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 14,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 15,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 16, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 17, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 18,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 21,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 22,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 23, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 24, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 25,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 28,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 29,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 30, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 31, week_day: "Domingo", is_holiday: false, is_weekend: true },
    ],
  },
  {
    id: 4,
    name: "Abril",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 1,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 2, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 3,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 4,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 5, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 6, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 7, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 8,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 9, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 10,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 13, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 14, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 15,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 20, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 21, week_day: "Domingo", is_holiday: true, is_weekend: true }, // Tiradentes
      {
        day: 22,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 25,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 27, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 28, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 29,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 30,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 5,
    name: "Maio",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
      },
      { day: 1, week_day: "Quarta-feira", is_holiday: true, is_weekend: false }, // Dia do Trabalho
      {
        day: 2,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 3, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 4, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 5, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 6,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 7, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 8,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 9,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 10,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 11, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 12, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 13,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 14,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 15,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 18, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 19, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 20,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 21,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 22,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 25, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 26, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 27,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 28,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 29,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 30,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 31,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 6,
    name: "Junho",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_5",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_6",
        is_holiday: true,
        is_weekend: false,
      },
      { day: 1, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 2, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 3,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 4, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 5,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 6,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 7, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 8, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 9, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 10,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 14,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 15, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 16, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 17,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 21,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 22, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 23, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 24,
        week_day: "Segunda-feira",
        is_holiday: true,
        is_weekend: false,
      }, // São João (feriado regional em alguns estados)
      {
        day: 25,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 28,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 29, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 30, week_day: "Domingo", is_holiday: false, is_weekend: true },
    ],
  },
  {
    id: 7,
    name: "Julho",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 1,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 2, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 3,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 4,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 5, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 6, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 7, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 8,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 9, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 10,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 13, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 14, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 15,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 20, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 21, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 22,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 25,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 27, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 28, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 29,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 30,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 31,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 8,
    name: "Agosto",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 1,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 2, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 3, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 4, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 5,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 6, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 7,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 8,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 9, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 10, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 11, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 12,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 14,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 15,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 17, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 18, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 19,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 21,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 22,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 24, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 25, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 26,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 28,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 29,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 30,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 31, week_day: "Sábado", is_holiday: false, is_weekend: true },
    ],
  },
  {
    id: 9,
    name: "Setembro",
    days: [
      { day: 1, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 2,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 3, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 4,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 5,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 6, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 7, week_day: "Sábado", is_holiday: true, is_weekend: true }, // Independência do Brasil
      { day: 8, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 9,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 10,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 14, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 15, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 16,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 21, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 22, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 23,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 25,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 28, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 29, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 30,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 10,
    name: "Outubro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      { day: 1, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 2,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 3,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 4, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 5, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 6, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 7,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 8, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 9,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 10,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 12, week_day: "Sábado", is_holiday: true, is_weekend: true }, // Nossa Senhora Aparecida
      { day: 13, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 14,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 15,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 16,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 19, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 20, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 21,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 22,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 23,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 25,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 26, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 27, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 28,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 29,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 30,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 31,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
  {
    id: 11,
    name: "Novembro",
    days: [
      {
        day: 0,
        week_day: "blank_1",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_2",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_3",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_4",
        is_holiday: true,
        is_weekend: false,
      },
      {
        day: 0,
        week_day: "blank_5",
        is_holiday: true,
        is_weekend: false,
      },
      { day: 1, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 2, week_day: "Sábado", is_holiday: true, is_weekend: true }, // Finados
      { day: 3, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 4,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 5, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 6,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 7,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 8, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 9, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 10, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 11,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 14,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 15, week_day: "Sexta-feira", is_holiday: true, is_weekend: false }, // Proclamação da República
      { day: 16, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 17, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 18,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Quarta-feira",
        is_holiday: true,
        is_weekend: false,
      }, // Consciência Negra (feriado regional em alguns estados)
      {
        day: 21,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 22,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 23, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 24, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 25,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 26,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 28,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 29,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 30, week_day: "Sábado", is_holiday: false, is_weekend: true },
    ],
  },
  {
    id: 12,
    name: "Dezembro",
    days: [
      { day: 1, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 2,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 3, week_day: "Terça-feira", is_holiday: false, is_weekend: false },
      {
        day: 4,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 5,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 6, week_day: "Sexta-feira", is_holiday: false, is_weekend: false },
      { day: 7, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 8, week_day: "Domingo", is_holiday: true, is_weekend: true }, // Nossa Senhora da Conceição (feriado regional em alguns estados)
      {
        day: 9,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 10,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 11,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 12,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 13,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 14, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 15, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 16,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 17,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 18,
        week_day: "Quarta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 19,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 20,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 21, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 22, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 23,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 24,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 25,
        week_day: "Quarta-feira",
        is_holiday: true,
        is_weekend: false,
      }, // Natal
      {
        day: 26,
        week_day: "Quinta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 27,
        week_day: "Sexta-feira",
        is_holiday: false,
        is_weekend: false,
      },
      { day: 28, week_day: "Sábado", is_holiday: false, is_weekend: true },
      { day: 29, week_day: "Domingo", is_holiday: false, is_weekend: true },
      {
        day: 30,
        week_day: "Segunda-feira",
        is_holiday: false,
        is_weekend: false,
      },
      {
        day: 31,
        week_day: "Terça-feira",
        is_holiday: false,
        is_weekend: false,
      },
    ],
  },
];
